name: GitHub actions demo
run-name: Testing our Github actions

on: [push]

jobs:
  basic_workflow:
    runs-on: ubuntu-latest

    steps:
      - run: echo "job is executing as part of basic workflow"
      
